version: 2.1
executors:
  docker-builder:
    docker:
      - image: circleci/openjdk:11-jdk
  docker-azure:
    docker:
      - image: microsoft/azure-cli

jobs:
  build-software:
    # Build the application
    executor: docker-builder
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx1024m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Build dependency list
          command: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build software
          command: bash ./gradlew check
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
      - store_test_results:
          path: build/test-results/

  publish-sonar:
    executor: docker-builder
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Performing analysis
          command: ./gradlew sonarqube

  publish-javadoc:
    executor: docker-azure
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publishing documentation Azure
          command: |
            az storage blob upload-batch \
                --source ~/repo/target/site/apidocs \
                --destination $azureBlob \
                --destination-path java/language/snapshot \
                --connection-string $azureDocString

  release:
    executor: docker-builder
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Setup the PGP key
          command: |
            openssl aes-256-cbc -pass pass:$openSslPwd -md md5 -in private-key.gpg.enc -out signing-key -d
            gpg --batch --import signing-key
            shred signing-key
      - run:
          name: Obtain release version
          command: |
            export rawV=`mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout`
            mkdir ~/repo/target
            echo "${rawV//[A-Z\-]/}" >> ~/repo/target/version.file
      - run:
          name: Perform release
          command: |
            GPG_TTY=$(tty)
            git config --global user.email "release-agent@jong-soft.com"
            git config --global user.name "Release Agent"
            mvn -V -B -s settings.xml -P release-profile,sonar release:prepare release:perform -Dsonar.login=$sonarKey
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target
            - promo-site

  release-javadoc:
    executor: docker-azure
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Determine version
          command: export releaseVersion=`cat ~/repo/target/version.file`
      - run:
          name: Publish promo site
          command: |
            az storage blob upload-batch \
                --source ~/repo/promo-site \
                --destination $azureBlob \
                --destination-path project/language-extension \
                --connection-string $azureDocString
      - run:
          name: Publishing JavaDoc Azure
          command: |
            az storage blob upload-batch \
                --source ~/repo/target/site/apidocs \
                --destination $azureBlob \
                --destination-path java/language/$releaseVersion \
                --connection-string $azureDocString

workflows:
  version: 2
  commit-build:
    jobs:
      - build-software:
          filters:
            branches:
              ignore: /release\/.*/
#      - publish-javadoc:
#          requires:
#            - build-software
#          filters:
#            branches:
#              only: master
      - publish-sonar:
          requires:
            - build-software
          filters:
            branches:
              only: master
  release-build:
    jobs:
      - release:
          filters:
            branches:
              only: /release\/.*/
#      - release-javadoc:
#          requires:
#            - release
#          filters:
#            branches:
#              only: /release\/.*/
